version: "3.3"
services:
  app:
    container_name: "discord-planning-poker-bot-app"
    restart: unless-stopped
    build: .
    env_file: .env
    working_dir: "/app"
    command: python -O main.py
